name: Actions for Pull Request

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Actions running!"
